server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://39.99.156.245:3306/mjzblog?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  freemarker:
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  resources:
    static-locations: classpath:/static/
  redis:
    host: 39.99.156.245
    port: 6379
    password:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 39.99.156.245:9300
      repositories:
        enabled: true
  rabbitmq:
    username: root
    password: admin
    host: 39.99.156.245
    port: 5672
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
file:
  upload:
    dir: ${user.dir}/upload
