server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://39.99.156.245:3306/mjzblog?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    charset: UTF-8
    content-type: text/html; charset=utf-8
    suffix: .ftl
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
